### ISSUE TITLE
Release naming convention

### ISSUE THREAD

**Issue by michelleheh** [cloudfoundry-incubator/event-log-release#3]
Event Log Team,

We've noticed your initial release does not follow Cloud Foundry release naming convention. People typically use "-" instead of "_". For example, see Garden Runc Releases [Here](https://github.com/cloudfoundry/garden-runc-release/tree/develop/releases/garden-runc).

Is it possible for your next release you can change the tool to follow established standards.

Regards,
Michelle @joshzarrabi

**Comment by xtreme-sameer-vohra** [comment]
Thanks Michelle & Josh,
We have a story for this - https://www.pivotaltracker.com/story/show/152729560
